### ISSUE TITLE
in contribution guide window, only show the relevant sources

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#100]
![image](https://user-images.githubusercontent.com/1681677/48327742-b5f7a000-e640-11e8-8b02-9dcff6f642e9.png)

1) Don't show the OSM link as it is not applicable here
2) possibly show the link to wiki-commons as this is where it really is ?

**Comment by mmmatthew** [comment]
Agree. A refactorization and parametrization of the application is planned in order for the front-end to obtain detailed fountain parameter information from datablue. (see https://github.com/water-fountains/datablue/issues/12) 
This can be fixed easily once that is done.
