### ISSUE TITLE
german description not taken

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#106]
![image](https://user-images.githubusercontent.com/1681677/51679976-b9b08700-1fe0-11e9-8e8a-4bb5935ee365.png)
1) while being on German on our site, I noticed that 
2) the english wikidata description was taken. So far so good as no german description existed in wikidata
3) Then I added the german description in wikidata and pressed "refresh"

Unfortunately no change 

(or rather: the wikipedia citation disappeared   :(  )

**Comment by mmmatthew** [comment]
Many fountains in OpenStreetMap have descriptions without a specified language. This is a problem with user's contributions, but we might also build a workaround for proximap (in that case, a new issue should be created)
