### ISSUE TITLE
Improvement suggestions for Readme.md

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#109]
Now that I flushed the eclipse git clone and re-did it, I made progress.
Therefore, please

Re 1) say that a command-line git exe is needed (and that some IDE git like in Eclipse may cause problems)
Re 2) say that the drive you clone should have significant space available (was it 0.5 GB?)
Re 3) put a warning if the datablue backend server is not running

Furthermore, the below only seem to be optional dependencies. But is win64 really that exotic?
Would it be possible to make those disappear ?

26 hauser@Ralf15:/cygdrive/f/proximap $ npm install
npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular-devkit\core\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 22899 packages in 9.207s
found 0 vulnerabilities

**Comment by ralfhauser** [comment]
Further make the "http://localhost:4200" link klickable ( target="_blank")

**Comment by ralfhauser** [comment]
when sync with eclipse, src/environments/version.ts wants to be added - shouldn't that go into .gitignore

**Comment by mmmatthew** [comment]
This provides information for how to fix the fsevents warning: https://github.com/angular/angular/issues/13935
Regarding the datablue warning: these is a message in italic at the very beginning of the instructions. do you mean something else?

**Comment by ralfhauser** [comment]
npm -i -f 
worked for datablue.

With proximap, I still get

<<24 hauser@Ralf15:~/git/proximapF $ npm install
npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.

audited 22899 packages in 8.309s
found 0 vulnerabilities>>

**Comment by ralfhauser** [comment]
Just started proximap without datablue and the app comes up, but the mapbox part remains empty.

And I don't see a warning in 
![image](https://user-images.githubusercontent.com/1681677/52399574-fbe7c700-2abc-11e9-9a22-45e5c41b2bad.png)
