### ISSUE TITLE
Show warning if datablue not available

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#110]
Ralfhauser: Just started proximap without datablue and the app comes up, but the mapbox part remains empty.

And I don't see a warning in 
![image](https://user-images.githubusercontent.com/1681677/52399574-fbe7c700-2abc-11e9-9a22-45e5c41b2bad.png)

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/109#issuecomment-461332389_

**Comment by mmmatthew** [comment]
Does it make most sense to have such a warning in the command line or in the application itself. Since it is not an issue of proximap in itself, I chose the latter: 
![image](https://user-images.githubusercontent.com/10126798/52444399-89accc00-2b28-11e9-828f-8d8bf3c24180.png)

**Comment by mmmatthew** [comment]
@ralfhauser is this solution acceptable and can I close the issue?

**Comment by ralfhauser** [comment]
haven't tested it, but looks cool
