### ISSUE TITLE
show number of fountains in "zone" (e.g. "zurich") depending on construction year filter

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#114]
This is an extension of issue #71 

There should be a mouse-over or something alike that gives the number fountains left out of the total when the filter is applied

**Comment by mmmatthew** [comment]
This is a good idea, and I think the information should be provided more prominently. Right now the number of fountains shown after filtering is the second number at the bottom of the list. We could:
1. Move the summary to the top of the list
2. Indicate the total number of fountains in the city
3. Not indicate the number of fountains visible in the list presently (the first number shown right now
![image](https://user-images.githubusercontent.com/10126798/53641884-95277a80-3c30-11e9-9356-c60d9336b1e4.png)
