### ISSUE TITLE
add a filter whether water is drinkable or not

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#116]

**Comment by mmmatthew** [comment]
The filter needs to take into account the fact that sometimes no information is available and sometimes the answer in neither true nor false. The same goes for #117 and #118

**Comment by ralfhauser** [comment]
minor glitch in https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55169808

![image](https://user-images.githubusercontent.com/1681677/54876553-39f13e00-4e12-11e9-993e-8b585d41b232.png)

**Comment by ralfhauser** [comment]
2) btw, it is "Flasche_**n**_füllung"

**Comment by mmmatthew** [comment]
the spelling has been corrected
