### ISSUE TITLE
better call to action on missing name

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#120]
e.g. https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55166058

![image](https://user-images.githubusercontent.com/1681677/53283952-b4646a80-374d-11e9-8d89-76ef65142c95.png)

**Comment by ralfhauser** [comment]
1) In German it is "Unbenannter Brunnen" ==> "r" is missing
2) I suggest you use an icon here - either your plus or something along 
![image](https://user-images.githubusercontent.com/1681677/53283993-1d4be280-374e-11e9-9ef6-928385fca248.png)

**Comment by ralfhauser** [comment]
3) currently, there is no title/mouse-over - it should be something like
"Kennen Sie den Namen dieses Brunnens? Falls ja, bitte in Wikidata:*propertyName* anfügen!"

**Comment by mmmatthew** [comment]
related to #137

for 3: The instructions should actually be more precise and accurate. I doubt that the title is an appropriate place for this information. For example, maybe the fountain only has an entry in OSM.  So I would propose a simple title:  "Können Sie mit dieser Informationslücke helfen?"

**Comment by mmmatthew** [comment]
For 2: how about a pencil icon: ![image.png](https://images.zenhubusercontent.com/5c87b7692bed174f657cd025/b30a9c7b-95ec-4529-8fdd-3b982522eaa1)

**Comment by ralfhauser** [comment]
Re 3) please do the title WITH the "(Wikidata|OSM|commons.media...):propertyName" as a short term measure

4) furthermore, pls make a concrete suggestion where you want to be "more precise and accurate"

**Comment by mmmatthew** [comment]
re 3) sometimes both osm and wikidata contain the property, but under different names. Do you suggest showing all possibilities? by clicking the button you will be presented with this information directly in the property dialog (when #122 pt 2 is implemented)

re 4) we have detailed contribution guides for fountain properties: 
![image](https://user-images.githubusercontent.com/10126798/54926685-19f47400-4f11-11e9-8e1b-531aaa6eedf6.png)

**Comment by ralfhauser** [comment]
re 3) yes, add "all" as long as this is < 70 characters (otherwise truncate and add "...").

**Comment by ralfhauser** [comment]
re 4) Let's re-assess, once https://github.com/water-fountains/proximap/issues/122 is implemented

**Comment by mmmatthew** [comment]
The whole st

> re 3) yes, add "all" as long as this is < 70 characters (otherwise truncate and add "...").

The whole string is a bit more than 100 in German so I just leave it as such.

**Comment by ralfhauser** [comment]
re 2) you didn't like the two icon proposals ?

**Comment by mmmatthew** [comment]
The icon with the light bulb invokes getting an idea and being creative. I don't think we want people to just think up names for fountains. The information contributed should be pre-established.

**Comment by mmmatthew** [comment]
The plus symbol signifies adding, which for me works but I feel it is more the idea of editing that we are after (since there is a text that is already displayed)
