### ISSUE TITLE
ideas to facilitate contributions

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#122]
e.g. in https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55169550 

![image](https://user-images.githubusercontent.com/1681677/53284138-250c8680-3750-11e9-9304-2cd282cde586.png)

**Comment by ralfhauser** [comment]
1) on mouse-over say: "Wikidata:ground level 360 degree view"

**Comment by ralfhauser** [comment]
2) if you click here, you still don't see it, so inside the red circle
![image](https://user-images.githubusercontent.com/1681677/53284165-93514900-3750-11e9-93b5-6f1ab41d693a.png)

say: Add property "1. ground level 360 degree view"

**Comment by mmmatthew** [comment]
1. Conflicts with proposition to add contribution hints, see #123 pt 2. I propose writing property description instead.
2. This is a good idea, can be done.

**Comment by ralfhauser** [comment]
Re 1) need not to be seen as a conflict
Therefore, pls
1a) mention property "ground level 360 degree view"
1b) add short instruction how to contribute

**Comment by mmmatthew** [comment]
It is helpful if the issue title reflects the full content of an issue. Please update your issue title or consider creating separate issues.

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/55280011-16515a80-5320-11e9-86d6-b2bdf00268fc.png)

A lot of useful information is here, but a novice may not understand it.
5) We should try to make it clear that above the red-line, this explains the "current state" and below the red line, it is "how to contribute/improve the underlying data of the fountains app"

**Comment by mmmatthew** [comment]
Or we put the value within the wikidata section, to clearly show that it was taken from there. If for a property à value is also found in osm, then both can be displayed without confusion.

**Comment by ralfhauser** [comment]
pls draw a mock up/equisse that makes this thought clear

**Comment by ralfhauser** [comment]
Re 1a) ist still only numeric and not as described
Please amend property name
![image](https://user-images.githubusercontent.com/1681677/55836738-ad3bc500-5b1f-11e9-9054-133e53ef70e9.png)

**Comment by ralfhauser** [comment]
Also 2) is not as described initially: As we want humans to work on it, also below pls amend the property name
![image](https://user-images.githubusercontent.com/1681677/55836893-16bbd380-5b20-11e9-8c2b-028bea3f62a6.png)

**Comment by mmmatthew** [comment]
1 and 2 are fixed in the following commits:

https://github.com/water-fountains/proximap/commit/47bea516b2b68cf7c7563232e1caff84f9f9fcd6

https://github.com/water-fountains/datablue/commit/bb2a98780e93afcceda57db87969317f322290b3
