### ISSUE TITLE
Show contribution hints for featured image.

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#123]
E.g. https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q27230182 

1) water-mark
2) 
![image](https://user-images.githubusercontent.com/1681677/53284228-9436aa80-3751-11e9-8613-9713cea02728.png) 
add title that says: i) upload your image to commons.wikimedia, ii) link to it from wikidata

**Comment by ralfhauser** [comment]
3) once you click on "n/a" provide truly helpful hint:
![image](https://user-images.githubusercontent.com/1681677/53284268-1cb54b00-3752-11e9-91f9-83139a1d506d.png)

**Comment by mmmatthew** [comment]
The issue title and issue content do not match. I have created #136 and will change this title.

**Comment by mmmatthew** [comment]
1 - Additionally, contribution guide should appear under the link. 
2 - It is more intuitive if the title of a property describes the property. For Hauptbild, for example, the title would be "Name of the featured image as documented in Wikidata. This is useful for creating the gallery object, but otherwise not used directly."

**Comment by ralfhauser** [comment]
It is important to also show the *exact* name of the property

**Comment by mmmatthew** [comment]
Yes, the name of the property used at the source should be indicated at the location indicated at your point 3. The exact name is usually not the same for OSM and Wikidata

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/55279938-143acc00-531f-11e9-89e4-769a8c8ccb9b.png)

is not specific enough

**Comment by ralfhauser** [comment]
6) please add an appropriate screenshot in each version of the guide
![image](https://user-images.githubusercontent.com/1681677/55279968-7e537100-531f-11e9-8b4a-47ddd14c3ff9.png)

**Comment by ralfhauser** [comment]
Feedback from Katja: in contribution guide
![image](https://user-images.githubusercontent.com/1681677/55831377-3c8eab80-5b13-11e9-85cf-4d7649a2cd49.png)
please open a new tab and do not have the guide window disappear when you upload an image

**Comment by mmmatthew** [comment]
"Contribution hints" are not the "contribution guide". I have moved all comments relating to the contribution guide to #156  and will hide them here.
