### ISSUE TITLE
use the open data transport api to select nearest station and show upcoming departures

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#124]
1) use an icon like 
![image](https://user-images.githubusercontent.com/1681677/53284378-cd701a00-3753-11e9-9cf6-9b810d9a3dd4.png)  or 
![image](https://user-images.githubusercontent.com/1681677/53284385-fb555e80-3753-11e9-882f-ed76d8b14ab0.png)

**Comment by ralfhauser** [comment]
The disadvantage of the current solution (![image](https://user-images.githubusercontent.com/1681677/53284397-35266500-3754-11e9-811b-1d1d8a09c4b9.png) ) with google (https://github.com/water-fountains/proximap/issues/36#issuecomment-466133837) is that the user has to type and enter starting location which is cumbersome.
With transport API 2 clicks suffice!

**Comment by ralfhauser** [comment]
2) and there are IMPORTANT governance reasons to add this !!!!!

(BTW, I select "feature" and not "bug" when creating this, but now, I don't see any traces of that choice)

**Comment by ralfhauser** [comment]
great first version
3) Please take a different icon than your google-maps link
4) if you click on the icon, the line, the stations appear - great. If you click a 2nd time, they should disappear again (like Brunneneigenschaften)
5) on the mouse-over, it says "powered by opendata.ch".  probably be more specific with "transport.opendata.ch

**Comment by ralfhauser** [comment]
6) in a later phase, also show the vertical climb/drop in m
   (e.g. in Lausanne, this may really be of interest)
7) or even later: show the stops on the map around the fountain 

Probably for both, I would ask https://github.com/fabian or christian.trachsel@sbb.ch

**Comment by mmmatthew** [comment]
regarding 3), I will move the google maps link to the navigation pane:

![image](https://user-images.githubusercontent.com/10126798/55224386-b455ff80-5210-11e9-85b9-67da6e9d2796.png)

This should avoid any confusion

**Comment by mmmatthew** [comment]
New version:
![image](https://user-images.githubusercontent.com/10126798/55226911-6e9c3580-5216-11e9-8d3c-6c1529f52b6f.png)

**Comment by ralfhauser** [comment]
Good idea to move the google maps off the main screen!

Verified - but how do we not forget 6) and 7) ? Do you want to make a new issue out of those?

**Comment by ralfhauser** [comment]
my last question re 6) and 7) so far ignored  :(

**Comment by mmmatthew** [comment]
I would rather say lost in the noise than ignored. I will make a new issue for you, but normally it is the responsibility of the feature requester to create a new request with a reference to related features. Appending feature requests to closed issues is a good way to lose track of things.

**Comment by mmmatthew** [comment]
Having created a new issue for 6 and 7, I will close this issue
