### ISSUE TITLE
Featured Image link does not work

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#125]
![image](https://user-images.githubusercontent.com/1681677/53286054-ffd84200-3768-11e9-93a1-075239b6f339.png)

e.g. in https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q27229889

**Comment by mmmatthew** [comment]
This is a tricky one. The property stored in wikidata is in fact a string and not a URL. However, it makes sense to display it here as a URL. We have the same situation for wikimedia commons, but there the property type is correctly listed as a string. 

Proposed solution: 
- change the property type to a new type `identifying_string`, which indicates that a URL can be derived from it.
- display the property as a string, but add a button next to it that opens a new tab with the derived URL.

**Comment by mmmatthew** [comment]
Strictly speaking, the featured image name is just a string. I have changed the data type accordingly.
