### ISSUE TITLE
possible to swim

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#132]
e.g. http://www.brunnenfuehrer.ch/brunnen/allschwilerplatz.htm

possible icon:
![image](https://user-images.githubusercontent.com/1681677/53391214-ef58df00-3995-11e9-8564-dae55a6f5676.png)

e.g. https://beta.water-fountains.org/basel?lang=de&queryType=byCoords&lat=47.5574918&lng=7.5693423 

seems that there is no wikidata property for "swimmable" or "bathable"

**Comment by mmmatthew** [comment]
Requires a wikidata property to be created and validated.

**Comment by ralfhauser** [comment]
https://www.wikidata.org/wiki/Q17456505 ("swimming place") might do it
in https://www.wikidata.org/wiki/Q61881745

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/55651044-aba09300-57e7-11e9-91d0-ca380be73f0e.png)

**Comment by ralfhauser** [comment]
Don't see it yet ?
![image](https://user-images.githubusercontent.com/1681677/55654531-f58e7680-57f1-11e9-93e7-8af2bc6f8fc8.png)

**Comment by mmmatthew** [comment]
The project was still building when you checked I have added badges to indicate build status in the information pane: 
![image](https://user-images.githubusercontent.com/10126798/56020376-4b3db400-5d07-11e9-9085-86990d68c398.png)

**Comment by ralfhauser** [comment]
more Basel:  https://www.google.com/maps/d/viewer?mid=14An4F58DfTw5IJYF9YK-VLtQ3Jk&ll=47.55971904592851%2C7.595102841769403&z=14

Jonas.Eckenfels@bs.ch
