### ISSUE TITLE
watermark images that are not curated as they are often really BAADDD

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#136]
Issue was previously #123

Whenever a fountain does not have either a featured image or a wikimedia category, then a Google StreetView image is used.

**Comment by ralfhauser** [comment]
The pop-up is a good start, but a watermark is still needed - see e.g.

https://codepen.io/YuvarajTana/pen/auiqx

**Comment by mmmatthew** [comment]
Here we go:
![image](https://user-images.githubusercontent.com/10126798/54869614-851c3a00-4d9b-11e9-856f-ab327530d0e6.png)

**Comment by ralfhauser** [comment]
Cool.

Since some are on target, maybe inside the font transparent ?

https://stackoverflow.com/questions/30050556/how-to-make-a-text-stroke-with-transparent-text

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/54976175-ced27380-4f99-11e9-9ecb-0edb533324be.png)

Classical politeness:  "Du" starting with capital "D"   ;)

**Comment by ralfhauser** [comment]
5) You don't like the "stroke" and inside fully transparent ?

**Comment by mmmatthew** [comment]
I didn't realize you wanted the inside fully transparent with a white stroke.

In my view, the use of stroke with transparent is an artistic feature that works best for text that is much larger than what we have. In our case, the addition of a stroke will make it both harder to read the text and harder to see what is behind. So I wouldn't recommend it.

**Comment by ralfhauser** [comment]
How about trying the stroke at our specific example and then comparing the two ?

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/55651755-f6230f00-57e9-11e9-83fe-5d4e1ebe5fb5.png)


![image](https://user-images.githubusercontent.com/10126798/55651660-a3e1ee00-57e9-11e9-804b-2abdca462f42.png)


```
<svg id="watermark" viewBox="0 0 10 2" style="
    position: relative;
    color: white;
    /* opacity: 0.5; */
    font-size: 86px;
    bottom: 250px;
    transform: rotate(300deg);
    -webkit-transform: rotate(-18deg);
    text-align: center;
    vertical-align: middle;
    text-shadow: 0 0 18px rgba(0,0,0,1);
">
  <text x="5" y="1" text-anchor="middle" font-size="1.5" fill="none" stroke-width=".03" stroke="#fff" font-family="sans-serif">not curated</text>
</svg>
```

**Comment by ralfhauser** [comment]
how does the upper look like, if you have a yet thinner line ?

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/56020121-b6d35180-5d06-11e9-854e-11a46c07a546.png)

For fountain 
https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55166814
```
<svg id="watermark" viewBox="0 0 10 2" style="
    position: relative;
    color: white;
    /* opacity: 0.5; */
    font-size: 86px;
    bottom: 250px;
    transform: rotate(300deg);
    -webkit-transform: rotate(-18deg);
    text-align: center;
    vertical-align: middle;
    text-shadow: 0 0 2px rgba(0,0,0,1);
">
  <text x="5" y="1" text-anchor="middle" font-size="1.5" fill="none" stroke-width=".015" stroke="#fff" font-family="sans-serif">not curated</text>
</svg>

**Comment by ralfhauser** [comment]
Yesterday's stroke version is wonderful !

**Comment by ralfhauser** [comment]
In German, it is partially cut off
![image](https://user-images.githubusercontent.com/1681677/56077221-e1daa580-5dd9-11e9-87c8-cbcc2ba10ed5.png)
https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q27229668

**Comment by mmmatthew** [comment]
I spent some time trying to fix it but didn't get it.
