### ISSUE TITLE
Property details should include link to property descriptions for sources

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#143]
![image](https://user-images.githubusercontent.com/10126798/54423597-4c33f380-4711-11e9-8df7-5a000674678b.png)

Near the link to OSM should be a link to https://wiki.openstreetmap.org/wiki/Key:drinking_water

**Comment by ralfhauser** [comment]
Great progress!

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/55279770-a2fa1980-531c-11e9-9b71-34158e04e335.png)
1) Shouldn't that be "statements" insetead of "claims"

**Comment by ralfhauser** [comment]
2) why do you say "wiki" instead of "wikidata" ?
3) since most people function less "numeric" than you and me, how about citing the exact P-Name such as "ground level 360 degree view" here ?

**Comment by ralfhauser** [comment]
please only label "In Review" if meaningful work has been done.
==> items 2 and 3 still pending

**Comment by mmmatthew** [comment]
re 2. if you follow the link, you see that both osm and wikidata have "wiki" pages describing properties. But I agree that a better name might be found. I haven't found it yet.

**Comment by ralfhauser** [comment]
re 2) "wiki" --> "property description page" or alike
