### ISSUE TITLE
add fountain property: youtube video url

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#145]
P1651 (YouTube video ID) exists e.g. for https://beta.water-fountains.org/basel?lang=de&queryType=byId&database=wikidata&idval=Q683514

originally part of #128, but this is a smaller task that is easier

**Comment by mmmatthew** [comment]
Solution includes video-embed and allows for multiple videos.
See

https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q27229673

https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55166441

**Comment by ralfhauser** [comment]
to bad one of the tinguely videos is restricted
![image](https://user-images.githubusercontent.com/1681677/55654181-fffc4080-57f0-11e9-9da2-7efcce8dbfce.png)

No clue whether is can programmatically tested before attempting to view it ?

**Comment by mmmatthew** [comment]
Issue created for non-viewable videos
