### ISSUE TITLE
new "contribution icons"

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#148]
![image](https://user-images.githubusercontent.com/1681677/54876685-61e1a100-4e14-11e9-9811-22516aec2630.png)

I love the idea and execution of these new items.

1) Already on the initial mouse-over, please extend "Flaschenfüllung: nicht definiert" with " - please help/contribute?"

**Comment by ralfhauser** [comment]
2) on 
![image](https://user-images.githubusercontent.com/1681677/54876721-c7ce2880-4e14-11e9-9964-123289211c75.png)
also say in bold red "please help/contribute!"

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/54951540-2d6d0280-4f44-11e9-9fd3-22b6bb32808a.png)

3) Before "Wert", add a line "Attribut"
in the current case, it would have the value "amenity=drinking_water"

(duplicate of #122 .2)

**Comment by mmmatthew** [comment]
Please only give issue specifications relevant to the current issue "new contribution icons". Points 2. and 3. pertain to how information should be displayed in the property dialog and should be moved and integrated with #122 for example.

**Comment by mmmatthew** [comment]
Clean fix for 2: 
![image](https://user-images.githubusercontent.com/10126798/55231589-6ac2e000-5223-11e9-999a-f74c53506b42.png)

**Comment by ralfhauser** [comment]
4) why are icons "pet-access-contribute" and "bottle-refill-contribute" not visible with
https://beta.water-fountains.org/lucerne?lang=de&queryType=byId&database=osm&idval=node%2F1158988930 ?

**Comment by mmmatthew** [comment]
They are only shown if the water is actually potable... I am not sure if that makes sense.

**Comment by ralfhauser** [comment]
Re 4) I understand for bottle fillable, but often dogs get to drink water humans wouldn't so the pet one should still be visible

**Comment by mmmatthew** [comment]
True, true

**Comment by mmmatthew** [comment]
This should be fixed now.
