### ISSUE TITLE
Include more details in contribution guides for media

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#156]
since wikidata and commons do not work well together, 
1) pls add specific screenshots in contribution guides.
https://www.wikidata.org/wiki/Q55170336

![image](https://user-images.githubusercontent.com/1681677/55294980-8f2be180-5408-11e9-8c67-0358aad868c2.png)

so let's try the two:

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/55294999-b387be00-5408-11e9-9e2b-01a3ae51b420.png)
![image](https://user-images.githubusercontent.com/1681677/55295009-c69a8e00-5408-11e9-9431-241908ba4fa3.png)

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/55295022-e9c53d80-5408-11e9-97d0-e8ffd7822509.png)

or the next one is truly absurd: the picture is found but still refused
![image](https://user-images.githubusercontent.com/1681677/55295034-12e5ce00-5409-11e9-9acf-735b19d2874b.png)

**Comment by ralfhauser** [comment]
Just the bare filename seems to work:
![image](https://user-images.githubusercontent.com/1681677/55295055-47f22080-5409-11e9-8744-0f5da74272bd.png)

**Comment by ralfhauser** [comment]
Just giving the name of the category also doesn't work
![image](https://user-images.githubusercontent.com/1681677/55295075-8091fa00-5409-11e9-899d-30f47f86c410.png)

Unless you have opened the category and properly saved it again, you get
![image](https://user-images.githubusercontent.com/1681677/55295089-afa86b80-5409-11e9-9a49-4a2160d5b7a8.png)
and then removed prefix "category:" - on the wikidata-side it finally works:
![image](https://user-images.githubusercontent.com/1681677/55295112-e2526400-5409-11e9-8ef4-7d77f771dbf5.png)
But only there - in the waterfountains-app, it still doesn't show as per
https://github.com/water-fountains/proximap/issues/155
==> what a hassle

**Comment by mmmatthew** [comment]
2) ![image](https://user-images.githubusercontent.com/1681677/55279938-143acc00-531f-11e9-89e4-769a8c8ccb9b.png)

is not specific enough

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/123#issuecomment-478272741_

3) [was 6)] please add an appropriate screenshot in each version of the guide
![image](https://user-images.githubusercontent.com/1681677/55279968-7e537100-531f-11e9-8b4a-47ddd14c3ff9.png)

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/123#issuecomment-478273034_

Feedback from Katja: in contribution guide
![image](https://user-images.githubusercontent.com/1681677/55831377-3c8eab80-5b13-11e9-85cf-4d7649a2cd49.png)
4) please open a new tab and do not have the guide window disappear when you upload an image

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/123#issuecomment-481413557_

**Comment by mmmatthew** [comment]
This has been tested with someone new to the project:
https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55169735
