### ISSUE TITLE
Show values from both OSM and Wikidata in the properties dialog

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#160]
![image](https://user-images.githubusercontent.com/10126798/55669045-f6b3b800-5872-11e9-8e31-6eed9800992c.png)

**Features**

- Show OSM and Wikidata side by side on large screens for easier comparison
- The most trusted source will be highlighted visually
- Show original value and extracted value for each source.  For example, original value might be a list of catalog codes, but the extracted value is just the catalog code corresponding to the fountain operator's id
- If any of the values are longer than a certain length (can easily happen with lists etc), then shorten (but show full value in title).
- OSM and Wikidata will always be shown, and always in the same order. If no fountain exists in a given source and/or if a property is not available for a given source, then messages will be displayed accordingly as discussed in #151.

**Notes**

- The conflict detection is a logical next step but is not included in this request
- The order and display details of the information, especially within the two boxes, will be adjusted/improved on as compared to the drawing above.

**Comment by ralfhauser** [comment]
Do we have an example fountain to illustrate this new format ?

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/59491870-f691f300-8e87-11e9-943d-a23c351e5da5.png)

https://beta.water-fountains.org/ch-zh?l=de&i=Q55169195

**Comment by ralfhauser** [comment]
which fountain is this wonderful screenshot from ?

**Comment by mmmatthew** [comment]
I added a link.
