### ISSUE TITLE
Link to further information for fountain artist

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#163]
This applies to fountain properties that are entities in themselves, such as fountain operators and artists

Let's take the example of https://www.wikidata.org/wiki/Q163938 Tinguely
Pls show in _new tab 
10) wikipedia entry 
    or if not existing
11) "described by source" - Reference URL 
    or if not existing
12) "described at URL"
    or if not existing
13) URL

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/129#issuecomment-481224696_

**Comment by ralfhauser** [comment]
or if not existing
14) "official website"

**Comment by mmmatthew** [comment]
Special case for artist information
> 15) a "museum" is named after artist AND has URL as per #163
> (e.g. https://www.wikidata.org/wiki/Q180904 Tinguely Museum)

(originally posted in #129)

**Comment by mmmatthew** [comment]
if an artist has a museum named after them, it would be very strange that they don't have a wikipedia page, no? How about we first deal with special cases that actually exist before preparing for hypothetical situations.

**Comment by ralfhauser** [comment]
do you have a example case for each of the cases 10 through 15 ?

btw 15) is "link to the artist wikidata entry" and suggest to add a web-link there  (seems to exist already)

**Comment by mmmatthew** [comment]
examples:
10) Wikipedia: Q1760194
11) Official website: No example found.
12) Described at URL: Q27229903
13) URL: No example because this property should not be used for fountains. The property is for the "URL of a resource" ie where a resource can be found online.
15) No url: Q27230047
