### ISSUE TITLE
offer image reload if no image shows in gallery details

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#166]
e.g. Zürich Rebekkabrunnen just shows
![image](https://user-images.githubusercontent.com/1681677/55852609-00346d00-5b5e-11e9-84dc-8e23c7b60395.png)

currently, only 2 out of 20 images are not black  :(

**Comment by mmmatthew** [comment]
Can you confirm that reloading solves this problem? When I tested it, it didn't help. As mentioned in https://github.com/water-fountains/proximap/issues/126, it is a problem with the library used.

**Comment by ralfhauser** [comment]
After multiple reloading, https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.3670189&lng=8.5400145 Rebekkabrunnen right now only shows 2 out 20 images :(

I guess you'll have to dig into what this library does in more detail and provide the maintainer with more specific bug reports/rfe's or to replace the library with another one

This is a BLOCKER for going out of Beta

**Comment by mmmatthew** [comment]
An issue has been opened: MurhafSousli/ngx-gallery#272 where the problem is discussed.

This issue will be marked as a duplicate to #126 and closed. 

I will label with "won't fix" because image reloading does not appear to solve the problem.
