### ISSUE TITLE
cell: allow to filter on small screens too

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#167]
it would be nice

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/55853711-98ccec00-5b62-11e9-8a8a-9767d6168709.png)

Does this not open the filter pane for you?

**Comment by ralfhauser** [comment]
Yes, it does - sorry for the confusion - pls close.

(I can not close it)

**Comment by mmmatthew** [comment]
okay.
