### ISSUE TITLE
Show all fountains if date filter value lies in future

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#173]
Shouldn't that be 212 of 212 ?
![image](https://user-images.githubusercontent.com/1681677/55293926-28083000-53fc-11e9-8aa6-f0f7a84d2b9e.png)

1) please make a mouse-over explaining that "no date" are not included in filter
2) if date >= now, always include all fountains

_Originally posted by @ralfhauser in https://github.com/water-fountains/proximap/issues/154#issuecomment-478372810_

**Comment by mmmatthew** [comment]
@ralfhauser, I do not think we should implement 
> if date >= now, always include all fountains

It would imply that so many fountains were built in the present year, which is false.
If we set the display condition to be some year in the future, it would imply that the date data is false, which is also misleading.

**Comment by mmmatthew** [comment]
With the mouse-over, I think we achieve clarity and precision. If users want to see all fountains, they just deactivate the filter.

![image](https://user-images.githubusercontent.com/10126798/56076155-b487fa80-5dcd-11e9-9e35-563669b452b2.png)

**Comment by ralfhauser** [comment]
> It would imply that so many fountains were built in the present year, which is false.

I don't understand this and I think this statement is logically wrong

**Comment by ralfhauser** [comment]
but the better approach is probably not to offer 2020 if we are not yet 2020 because this is asking for troubles

same with 2030 etc.

**Comment by ralfhauser** [comment]
Let me refine 1) 
  if date == now, always include all fountains with no date or a date <= now


(this under the assumption that if someone is already creating a wikikdata item for a fountain in planning/"under construction", s/he'll at least put a date)

**Comment by mmmatthew** [comment]
I see what you mean. Could you check the German pop up text?

**Comment by ralfhauser** [comment]
> I see what you mean. Could you check the German pop up text?

It is good. Maybe just change the order of the last 2 words
<<... und "vor" ausgewählt ist.>>

**Comment by mmmatthew** [comment]
Fixed.

**Comment by ralfhauser** [comment]
if you change the year from 2020 down to 2019, the number of fountains immediately jumps from 1453 to 1001

#179 will explain this for the end-user
