### ISSUE TITLE
Wikimedia image names with quotes cannot be displayed in map

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#177]
For example for this fountain:
~~http://localhost:4200/zurich?lang=de&queryType=byCoords&lat=47.3666835&lng=8.5405953~~

https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.3666835&lng=8.5405953

**Comment by ralfhauser** [comment]
You probably meant
https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.3666835&lng=8.5405953

**Comment by ralfhauser** [comment]
Got it ![image](https://user-images.githubusercontent.com/1681677/56075810-f06c9100-5dc8-11e9-86bf-26252e47dc9b.png)

1) Is that an escaping problem in a library?
2) If so, can you make an bug report there and cite it here ?

**Comment by mmmatthew** [comment]
No, the problem is on our side.
