### ISSUE TITLE
optimizing for mobile use: responsive font sizes

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#181]
The fonts of texts that need to be touched are too small (yellow marked)
![image](https://user-images.githubusercontent.com/1681677/56093974-0bc1c400-5ecf-11e9-8a30-31615d98db74.png)

**Comment by ralfhauser** [comment]
Suggestions
1 a) do not define the font-size "Inline" but via a .css style-sheet
1b) make the depending of the screen-size >= 2em  - e.g. by putting in

@media screen and (max-width: 575px) { 
    .... 2.3 em;

**Comment by ralfhauser** [comment]
or instead of "max-width" make it dependent on "touch" as per https://github.com/water-fountains/proximap/issues/74#issuecomment-475421056

**Comment by mmmatthew** [comment]
I have increased the font size and clickable area, but not quite as much as you suggested:

![image](https://user-images.githubusercontent.com/10126798/57536651-e47edb00-7344-11e9-944c-bcd1ad6a6d96.png)

**Comment by ralfhauser** [comment]
The font could be bigger - but only for small screens !!!
(did you see my suggestion in this respect?)

**Comment by ralfhauser** [comment]
in the normal PC browser, this
![image](https://user-images.githubusercontent.com/1681677/57537657-0bd6a780-7347-11e9-8db2-27ff7de12cf0.png)
should not grow!
(it feels like it did since yesterday  :( )

**Comment by mmmatthew** [comment]
> The font could be bigger - but only for small screens !!!
> (did you see my suggestion in this respect?)

Yes, I saw the 2.3 em suggestion and tested it and it seemed too big.

**Comment by mmmatthew** [comment]
> in the normal PC browser, this
> ![image](https://user-images.githubusercontent.com/1681677/57537657-0bd6a780-7347-11e9-8db2-27ff7de12cf0.png)
> should not grow!
> (it feels like it did since yesterday :( )

The font size should be exactly the same as before.

**Comment by ralfhauser** [comment]
Good for PC!

For Mobile, I still find the fonts too small

Pls apply the same screen-size dependent css-style also to the filtering GUI

**Comment by mmmatthew** [comment]
Given that the filter already takes up most of the vertical space on
mobile, increasing font size might make it hard to navigate. We should
consider moving all the filters except the text filter to the pop-out
described in #162. In the pop-out we can make the font size as large as
needed.

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/57571210-54f02f80-740b-11e9-9658-67976030faad.png)

Adding more space between the lines on mobile would already increase the touch-usability a lot

While I see the advantage of pop-out for large laptop screens, I don't see them for mobile since the extra space between the side bar and the pop-out is negligible

**Comment by mmmatthew** [comment]
After spending 1-2 hours trying to figure it out, I was not able to detect touch capability with css as suggested in https://medium.com/@ferie/detect-a-touch-device-with-only-css-9f8e30fa1134. So I just increase font size or add padding for small screens < 900px wide.
