### ISSUE TITLE
enable preview pictures for lucerne

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#185]
currently, they work in Zürich, but not in Lucerne

https://beta.water-fountains.org/lucerne?lang=de&queryType=byId&database=wikidata&idval=Q62599999

?

**Comment by mmmatthew** [comment]
That fountain shows a preview for me:

![image](https://user-images.githubusercontent.com/10126798/56375109-f61d0900-6204-11e9-8178-31a7e723cbb9.png)

But it appears that there are duplicate fountains in Lucerne. If for a duplicate pair one fountain has an image and the other doesn't, the image might not always appear.

**Comment by ralfhauser** [comment]
now it appears for me as well - 
1) there is something broken with city-reload/refresh - how does one reload an entire city ?
2) do you want to tell me that there specifically is a duplicate for Fritschibrunnen ?

**Comment by ralfhauser** [comment]
re 1) see #188

**Comment by ralfhauser** [comment]
Any comment to 2) or other ch-lu duplicates ?

**Comment by mmmatthew** [comment]
I cannot comment. This issue does not appear to be reproducible, so it is hard to say what the cause is. The issue mentioned in 2) with regards to duplicates impacting preview images is a problem I noticed but did not take time to investigate in detail.

**Comment by ralfhauser** [comment]
ok, let's hope this will not come back
