### ISSUE TITLE
commons category with images ignored

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#186]
Just uploaded the first images to HB and linked them to https://www.wikidata.org/wiki/Q55170765

Steps to reproduce:
1) open details of gleis4 grey fountain:  https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55170765
2) press refresh at the bottom of the detailed window.

Result:
a) on mouse-over the correct refresh time is displayed, but the image doesn't show
b) after refresh, the detail window is no longer visible by Q-number, but by coordinates
https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.37787142&lng=8.53789497

**Comment by ralfhauser** [comment]
after roughly 4 minutes and 3+ detail-window-reloads, the first pic in the category shows ?!?

**Comment by ralfhauser** [comment]
seems that the 2nd pic never is found.
Is it possible that this is due to it being
c) > 8MB (high resolution?)
d) thin and high in dimensions ?

**Comment by ralfhauser** [comment]
same delay in seeing it when using Image (P18) in https://www.wikidata.org/wiki/Q55170013 

https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55170013

(so far not just a delay, but simply ignored it)

**Comment by ralfhauser** [comment]
e) seems that https://www.wikidata.org/wiki/Q55170031 or rather https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q55170031 has no OSM entry and there the detail-refresh works while https://www.wikidata.org/wiki/Q55170762 i.e. https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.379291&lng=8.536953 has an OSM entry and there the detail-refresh doesn't work

**Comment by mmmatthew** [comment]
The issue appeared to be linked with PNG format not being expected in the image gallery.
Bug should be fixed with https://github.com/water-fountains/datablue/commit/9a6cf9f33dd8282f5aaf055dfd62e90f99c5073a
