### ISSUE TITLE
Transparency on city-scans - was: wikidata fountain not shown in Geneva

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#188]
https://www.wikidata.org/wiki/Q63239188 doesn't show despite reloads of site geneva

**Comment by mmmatthew** [comment]
Reloading the front-end web page "beta.water-fountains.org" does not re-process the data for the whole city. The fountain seems to appear now.

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/56558128-eb17ff00-659d-11e9-8223-17daa1d43717.png)
1a) Please say as of which date the city was last scanned
2) on mouse-over give the date here as well

1b) pls say also when/how the next scan will happen

**Comment by ralfhauser** [comment]
Re 1b)  Matthew last Friday: "every 2 hours" - see also #198
