### ISSUE TITLE
Processing fails for Lucerne location

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#192]
**Describe the bug**
Processing fails silently and http request returns nothing.

To reproduce: 
https://water-fountains.org:3000/api/v1/fountains?city=lucerne&essential=true

**Comment by mmmatthew** [comment]
Error is caused because of image with Chinese characters:

https://commons.wikimedia.org/wiki/File:%E7%91%9E%E5%A3%AB%E5%8D%A2%E5%A1%9E%E6%81%A9_Lucerne,_Switzerland_Luzern,_Schweiz_Lucerna,_Svizzera_Cina_Xinjiang,_Urumqi_il_benvenuto_alla_visita_della_citt%C3%A0_China_Xinjian_-_panoramio_(15).jpg

**Comment by mmmatthew** [comment]
The request to get image metadata works in the browser but fails in the script:

https://commons.wikimedia.org/w/api.php?action=query&titles=File:%E7%91%9E%E5%A3%AB%E5%8D%A2%E5%A1%9E%E6%81%A9_Lucerne%2C_Switzerland_Luzern%2C_Schweiz_Lucerna%2C_Svizzera_Cina_Xinjiang%2C_Urumqi_il_benvenuto_alla_visita_della_citt%C3%A0_China_Xinjian_-_panoramio_(15).jpg&prop=imageinfo&iiprop=extmetadata&format=json

**Comment by mmmatthew** [comment]
to solve: apply `encodeURIComponent()` to image title (`encodeURI` is not sufficient).

**Comment by mmmatthew** [comment]
image with special charcters not showing (again?)

**Comment by ralfhauser** [comment]
Please make the code more robust such that in such a case only one fountain disappears and not an entire city.

Probable approach:  

   try {
       ...
   } catch () {

**Comment by ralfhauser** [comment]
1) if you reach the catch{}-Block put the fountain with red on the map and show the error message as name

**Comment by mmmatthew** [comment]
> Please make the code more robust such that in such a case only one fountain disappears and not an entire city.
> 
> Probable approach:
> 
> try {
> ...
> } catch () {

Such errors will be handled in the future by filling the metadata with an error message:
https://github.com/water-fountains/datablue/commit/29f93309b216acd8789b23410478f9f710e0ae6e

**Comment by mmmatthew** [comment]
> 1. if you reach the catch{}-Block put the fountain with red on the map and show the error message as name

I am guessing this is what is keeping this issue open.
Should we turn this into a more general issue that would apply to any fountain processing issues and not only this one?

**Comment by ralfhauser** [comment]
sure

**Comment by mmmatthew** [comment]
I have opened a new issue and will close this one.
