### ISSUE TITLE
"dog" Field is not accepted by OSM

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#204]
To https://www.openstreetmap.org/node/3112091726 , I tried add the dog feature (after all, JuliaHottingen even took a detail picture of it)

**Comment by ralfhauser** [comment]
comparing with other fountains, I see that "dog" is not a "field", but a "tag".

==> pls make this clear in the contribution support

**Comment by mmmatthew** [comment]
Would this representation be clear?

![image](https://user-images.githubusercontent.com/10126798/57469662-6f999b80-7287-11e9-90ce-20018643fed8.png)

**Comment by ralfhauser** [comment]
Perfect
