### ISSUE TITLE
make detailed property processing information multilingual

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#209]
To expand the pool of possible contributors, property contribution information should not only be in English but also in German and French. This concerns the information at the following locations (both for wikidata and OSM):

![image](https://user-images.githubusercontent.com/10126798/57537551-d0d47400-7346-11e9-82c2-5095bd9e8a2e.png)

**Comment by ralfhauser** [comment]
see also #207

**Comment by mmmatthew** [comment]
Duplicate of #207
