### ISSUE TITLE
when creating a wikidata fountain and entering its id into OSM, after refresh, still does not show

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#211]
https://www.openstreetmap.org/node/1032369425
i.e.
https://beta.water-fountains.org/zurich?lang=de&queryType=byCoords&lat=47.3706268&lng=8.5344897

![image](https://user-images.githubusercontent.com/1681677/57570492-df806100-7402-11e9-97d9-50d6d7bc1729.png)

and after refresh still

![image](https://user-images.githubusercontent.com/1681677/57570501-0179e380-7403-11e9-8441-30920669e153.png)

**Comment by mmmatthew** [comment]
OSM takes a few minutes before the changes become available. This may be
the reason you did not see the change (it is visible now, I think).

>

**Comment by ralfhauser** [comment]
Right, this is already mentioned in the long text on the bottom of the 34 properties - sorry for bothering
