### ISSUE TITLE
image not found despite refresh

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#212]
https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q63715939

https://commons.wikimedia.org/wiki/File:Brunnen_27.jpg exists and is mentioned in https://www.wikidata.org/wiki/Q63715939 but doesn't show.

Admitted, the wikidata doesn't have the coordinates, but if OSM has the wikidata ID (#211) is that really still needed ?

**Comment by mmmatthew** [comment]
Currently, only fountains with coordinates, are collected from wikidata.

I would also note that from the image, it appears to be a pond and not a
well. Many fountains are falsely labeled as wells or water wells in
wikidata.

**Comment by ralfhauser** [comment]
1) let's also collect wikidata fountains without coordinates, provided they are referenced by OSM where that has a coordinate

2) I added "instance of pond" - you really think there are many ?

**Comment by mmmatthew** [comment]
2. Yes there are many: all the red and green dots here
https://tools.wmflabs.org/wikishootme/index.html#lat=47.366228237972294&lng=8.532457722049003&zoom=14&sparql_filter=%3Fq%20wdt%3AP31%2Fwdt%3AP279*%20wd%3AQ43483

If you check the definition of "well" in wikidata, you will see that it
does not apply to most of them and should actually be removed.

**Comment by ralfhauser** [comment]
3) suggest to be even more relaxed: if 
a) a fountain has an osm entry linking to a wikidata Q-ID and no pic otherwsie, but wikidata entry has an image, show it
b) in the merging algorithm search also for "tap" Q656656 (e.g. https://www.wikidata.org/wiki/Q64015724)

**Comment by mmmatthew** [comment]
I understand that you are suggesting 3 a) as a replacement for 1. However, 1 is more straightforward to implement.

**Comment by ralfhauser** [comment]
pls start with 1) and keep the issue open until 3) is done

**Comment by katjahenke** [comment]
Hi Matthew
Any news on https://github.com/water-fountains/proximap/issues/212? 
It would be terrific if it could be solved by Thursday morning, before we go on our Fountain-Tour. Any Chance? Happy Monday, Katja

**Comment by katjahenke** [comment]
One more time....
https://github.com/water-fountains/proximap/issues/212

**Comment by mmmatthew** [comment]
I can try to solve it this morning.

**Comment by katjahenke** [comment]
Terrific, thank you

 

 

Von: mmmatthew <notifications@github.com> 
Gesendet: Monday, 27 May 2019 08:22
An: water-fountains/proximap <proximap@noreply.github.com>
Cc: katjahenke <katjahenke@aol.com>; Comment <comment@noreply.github.com>
Betreff: Re: [water-fountains/proximap] image not found despite refresh (#212)

 

I can try to solve it this morning.

**Comment by mmmatthew** [comment]
@katjahenke can you check that the issue is fixed?

**Comment by katjahenke** [comment]
Yes, it's done! Many thanks
Katja

**Comment by katjahenke** [comment]
Hi Matthew
Julia and I keep running into the same issue....
We uplad a photograph but when we atempt to refresh the fountain info/pic, it does not change the picture.
Q64213962  
Q64214288 
Q55170723 
Q55166214
Q147276
Q64220833
Q64220847
Q64220859
Please let us know what we are doing wrong.
Thank you

**Comment by mmmatthew** [comment]
Hi Katja,
I took a quick look at some of your Wikidata entities, and suspect that
there is a problem with the data entry in Wikidata.

In order for a fountain to appear, the Wikidata item should have the
following information provided:
- the statement `instance of``fountain` and/or `drinking fountain`
- geographical coordinates

In the special case where the Wikidata entity is referenced in the
OpenStreetMap version of the fountain (see for example
https://www.openstreetmap.org/node/1747364087), then the coordinates are
not needed in Wikidata.

Hope that helps

**Comment by katjahenke** [comment]
Hi Matthew,

Thank you for the feedback. All has been well noted.

We will make sure to adjust all entries accordingly.

Kind regards,

Katja

**Comment by mmmatthew** [comment]
After talking on the phone, we figured out that one issue is that Wikidata expects coordinates in the latitude - longitude order (like 47.3124, 8.7430), but they were being entered in the longitude-latitude format (like 8.7430, 47.32421).

**Comment by ralfhauser** [comment]
https://www.wikidata.org/wiki/Q64213962 looks a lot better, but
https://beta.water-fountains.org/ch-zh?l=de&i=Q64213962  still dies in an awkward, non-telling way (https://github.com/water-fountains/proximap/issues/206#issuecomment-498022284) - what is still wrong?

**Comment by mmmatthew** [comment]
Q64213962 is just a pond, so it is not indexed by datablue. According to the suggestion in https://github.com/water-fountains/proximap/issues/242#issuecomment-496383842, man-made ponds might also be included by datablue even though they are not fountains.

https://www.wikidata.org/wiki/Q63715939 does appear in water-fountains because it is falsely labelled as a well.

**Comment by ralfhauser** [comment]
> https://www.wikidata.org/wiki/Q63715939 does appear in water-fountains because it is falsely labelled as a well.

But once https://github.com/water-fountains/proximap/issues/242#issuecomment-496383842 is implemented, the problem will go away from Q63715939 ?

I also changed https://www.wikidata.org/wiki/Q64213962 to man-made-pond , so also that will then work ?

**Comment by ralfhauser** [comment]
https://www.wikidata.org/wiki/Q64513188 has duplicate https://www.wikidata.org/wiki/Q64213962 tried to do a merge
