### ISSUE TITLE
Facilitate differentiation between nearby fountains on map

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#222]
![image](https://user-images.githubusercontent.com/1681677/57807172-ee4b7880-7760-11e9-8af6-e15961a41c65.png)

With currently available max zoom, it is not possible to select all of those fountains individually (3 out of 4 are really there!)
Mostly  Drachenbrunnen shows up.
- [x] 1) Allow to zoom more
- [x] 2) at this magnification level, the circles should be smaller such that they have less overlap

**Comment by mmmatthew** [comment]
Good feedback. However, please choose a representative issue title for both requests and don't put one request into the title and one request in a comment.
