### ISSUE TITLE
Please add expert mode to fountain creation guide

### ISSUE THREAD

**Issue by katjahenke** [mmmatthew/water-fountains.org#231]
Due to high volume of our contirbutions we only need the two key links and don't need the rest of the guide. Therefore I suggest to add a check box at the following position. 
![grafik](https://user-images.githubusercontent.com/49615740/58052056-1ddcf500-7b54-11e9-95db-ed9432fa2a2f.png)

**Comment by mmmatthew** [comment]
Thanks for the suggestion. I guess the useful links to have would be:
- Wikimedia Commons page
- Upload Wizard
- Wikidata page

These links can actually be found by clicking the "external links" button at the bottom of the details pane. 
![image](https://user-images.githubusercontent.com/10126798/58247830-de342a00-7d5a-11e9-900a-7000788e7eb1.png)

Maybe these links should be made more prominent, e.g. as small icons in the subtitle of the details window.

**Comment by ralfhauser** [comment]
I agree 
![image](https://user-images.githubusercontent.com/1681677/58271007-5b779300-7d8b-11e9-9839-30482ca36cc8.png) does the job for experts 

==> low prio  (sorry didn't think of that when sitting next to the kind reporter)
