### ISSUE TITLE
on mobile, it is unclear that there are more cities

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#240]
![image](https://user-images.githubusercontent.com/1681677/58384673-ce2f7b00-7fe4-11e9-8edc-d6f6375d5a97.png)

who would guess that there is already Basel and Luzern ?

**Comment by ralfhauser** [comment]
Better but not good yet.
The problem is still that the scroll-bar to the right of the options disappears or is too narrov

**Comment by ralfhauser** [comment]
![image](https://user-images.githubusercontent.com/1681677/58538917-78cab800-81f6-11e9-890c-0dfaec24bb00.png)

1) scroll-bar not visible
2) I have no way to move it up or down to see Geneva and Zürich

**Comment by ralfhauser** [comment]
Will this also work for > 10 cities ?

**Comment by mmmatthew** [comment]
> Will this also work for > 10 cities ?

Probably not. When we get that far we can consider having a search function, scroll bar, map, full-screen popout, or some other clever solution
