### ISSUE TITLE
allow simple short deep link

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#244]
right now, 
https://beta.water-fountains.org/ch-zh?l=de&i=Q55169550
  works

at least, if the Q55169550 has coordinates or is referenced by an osm with coordinates

also 
   https://beta.water-fountains.org/?i=Q55169550
should work

1) with the Q-Numger you get the coordinates and 
2) with that the city
3) if no lang is specified, take the one from the browser request and if that is missing, the city's default language

(see also first idea of #35 )

**Comment by ralfhauser** [comment]
10) even simpler should also be possible:
https://beta.water-fountains.org/Q55169550
since the Q-number is unique
a) https://h2o.do/Q55169550 should also work

**Comment by ralfhauser** [comment]
10 b) and in analogy for OSM:  https://h2o.do/60030906

**Comment by mmmatthew** [comment]
> 10 b) and in analogy for OSM: https://h2o.do/60030906

it would have to be https://h2o.do/node/60030906 or https://h2o.do/way/60030906 since both nodes and ways are supported

**Comment by ralfhauser** [comment]
Re 10b) a subdirectory is fine
b1) and since I am a 'lazy typer", you certainly also would make a shorter alias like
  https://h2o.do/n/60030906   ;)

**Comment by mmmatthew** [comment]
The following have been implemented :
https://h2o.do/Q55169550
 https://h2o.do/60030906 for osm

**Comment by ralfhauser** [comment]
https://help.openstreetmap.org/questions/72686/a-fountains-coordinatesnode-id-by-tag-wikidataq to get fountains where in wikidata no coordinates are specified

**Comment by ralfhauser** [comment]
for fountains where coordinates are not in wikidata, but only in osm, but osm references wikidata, this may help https://help.openstreetmap.org/questions/72686/a-fountains-coordinatesnode-id-by-tag-wikidataq

**Comment by ralfhauser** [comment]
allow to put the short link also into the search window
