### ISSUE TITLE
add a legend what the color coding on the map means

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#245]
blue = drinking water
grey = unknown
black = not drinkable

1) is that correct ?

2) is that already explained to the end-user somewhere?
b) if not where do you suggest to put it ?

**Comment by ralfhauser** [comment]
3) when access is restricted, add to the bullet a little lock (not just a tap) 
![image](https://user-images.githubusercontent.com/1681677/58709447-7ca73780-83ba-11e9-9f6f-2c648d01f63d.png) as per #199

**Comment by ralfhauser** [comment]
4) currently no water as in #246

**Comment by mmmatthew** [comment]
1. yes
2. no

**Comment by mmmatthew** [comment]
- This should appear in a pop-up that appear when the page is opened 
- There should be an option to disable it opening in the future
- The initial pop-up should include a brief introduction to the application
- The legend should also be placed in the "about" pane in the side menu

**Comment by ralfhauser** [comment]
see also #259
