### ISSUE TITLE
link with zueriwieneu

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#254]
https://www.zueriwieneu.ch/

Each fountain should have a "broken" tap icon - e.g. 
![image](https://user-images.githubusercontent.com/1681677/59975800-90f6e280-95bc-11e9-8465-5f11fb20a671.png) and link to there with target _blank

e.g. at the bottom left next to the navigation icon

**Comment by ralfhauser** [comment]
C. Gees will ask mysociety how much it costs to program a way where when calling the app already with geo-coordinates , step 2 (and possibly also step 1) can be omitted.

![zueriWieNeuSteps](https://user-images.githubusercontent.com/1681677/60077502-632fac00-972a-11e9-84a9-ad64f5858ac1.jpg)

From: Gees Christian (GeoZ) <Christian.Gees@zuerich.ch> 
Sent: Dienstag, 25. Juni 2019 07:12
Cc: Brunner Tobias (GeoZ) <Tobias.Brunner@zuerich.ch>
Subject: AW: Auftruf von Züriwieneu

Sehr geehrter Herr Hauser
 
Danke für ihr Interesse an Züri wie neu.
 
Ein solcher Aufruf aus einer anderen Applikation (Übergabe einer Koordinate/Adresse) ist momentan nicht möglich. [...]

Trotzdem denkbar ist es natürlich. Was genau schwebt ihnen vor? Sie können gerne auch anrufen.
 
Freundliche Grüsse
Christian Gees
Leiter Geschäftsbereich GIS-Zentrum
Direktwahl +41 44 412 27 51
...

Stadt Zürich
Geomatik + Vermessung
GIS-Zentrum
Weberstrasse 5
8004 Zürich

Telefon +41 44 412 42 56
Fax +41 44 270 90 46
www.stadt-zuerich.ch/geoz

**Comment by ralfhauser** [comment]
10) also prefill "Kategorie" with "Brunnen/Hydranten"
11)  only show the button if the operator is WVZ

- Further observations: mysociety has a 911 emergency interface they don't open for the broad public
- they consider adding a origin request paramter to easily track which partner app caused which reports (that probably could also be done with the referer request header)
- if needed they consider some kind of app-peer-auth

**Comment by ralfhauser** [comment]
C. Gees suggests on 25.06.2019 13:04 to use this icon for the button
https://www.wikidata.org/wiki/Q64822020
![zueriWieNeuButtonPlacement](https://user-images.githubusercontent.com/1681677/60094732-317c0c80-974d-11e9-9583-04a1fe3f0590.jpg)
"... Mit einem Mouseover-Text könnte man ja erklären, was man meint. Ansonsten überlasse ich es Ihrer Kreativität. "

**Comment by ralfhauser** [comment]
C. Gees: Hier ein Beispiel [für voreingefüllte Kategorie]:
https://www.zueriwieneu.ch/report/new?longitude=8.530685020118254&latitude=47.37351830729645&category=Brunnen/Hydranten

**Comment by mmmatthew** [comment]
1) This can be implemented in a first stage by:
- providing the link template and image url in the location metadata https://github.com/water-fountains/datablue/blob/develop/config/locations.js

2) In a second stage,
a) the link template and image url can be generated automatically by querying the wikidata element for Zurich wie neu, to which the image and url template is linked
b) this will slow app loading time if datablue always performs the query before returning the location metadata

**Comment by ralfhauser** [comment]
Re 2b) this should not be done by every visiting user, but only every 2hrs during the global server-side data refresh ==> 99.X% will never notice this extra query

**Comment by ralfhauser** [comment]
https://beta.water-fountains.org/ch-zh?l=de&i=Q63382683 is private  and thus does not have operator WVZ and therefore shouldn't show the zueriwieneu link

similarly probably https://beta.water-fountains.org/ch-zh?l=de&i=Q65095943 (albeit that one probably has Gartenbauamt as operator and eventually should

**Comment by mmmatthew** [comment]
Thanks, good point. I mistakenly assigned zuriwieneu to all fountains in Zurich.
