### ISSUE TITLE
search on mobile phone no longer works - responsiveness

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#382]
Wenn ich auf die Lupe klicke (1)
![srch](https://user-images.githubusercontent.com/1681677/124793759-9a0e3e80-df4e-11eb-942a-91f87eb94d90.jpg)

 
Aber ausser dem Schliess-X (2) und dem Verschwinden der Lupe (3)
 
![srch1 jpg](https://user-images.githubusercontent.com/1681677/124793815-a8f4f100-df4e-11eb-982e-5e5a39a6769e.png)

fehlt die Tastatur (4) und die übrigen Such-Parameter (5)

**Comment by robstoll** [comment]
@ralfhauser I would be glad if you could test it again as I don't know how it looked like before

**Comment by ralfhauser** [comment]
> @ralfhauser I would be glad if you could test it again as I don't know how it looked like before
Danke - sieht vielversprechend aus.
