### ISSUE TITLE
include advanced wheelchair accessibility info

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#84]
e.g. value of 'limited' for https://www.openstreetmap.org/node/365379874

**Comment by mmmatthew** [comment]
This issue requires https://github.com/water-fountains/datablue/issues/27

**Comment by mmmatthew** [comment]
![image](https://user-images.githubusercontent.com/10126798/54832133-e40a8200-4cbb-11e9-9b49-04e3475169b5.png)
See https://beta.water-fountains.org/geneva?lang=de&queryType=byId&database=wikidata&idval=Q29700492

**Comment by mmmatthew** [comment]
any values that are not `yes` or `no` will be displayed in the badge. The badges are also now clickable to bring up the property details

**Comment by ralfhauser** [comment]
10) On 
![image](https://user-images.githubusercontent.com/1681677/54876771-bfc2b880-4e15-11e9-937b-ca73e3d20fbf.png)
do not just cite the value, but also say "Rollstuhl-Zugänglichkeit: limited" or alike

**Comment by mmmatthew** [comment]
fixed with https://github.com/water-fountains/proximap/commit/a071dde66c05bc3a519126fd1ec4cc9e10a6ef08
