### ISSUE TITLE
license and author link not clickable

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#87]
When I first click on it, the links are not followed, but the image enlarges
![image](https://user-images.githubusercontent.com/1681677/44666295-57932c00-aa18-11e8-873f-9080c24c6255.png)
(not that dramatic because I get a 2nd chance)

But even in the enlargement, clicking on the link again has no effect:
![image](https://user-images.githubusercontent.com/1681677/44666337-72fe3700-aa18-11e8-82c3-94cb7323a9d1.png)
==> it seems that
a) ' target="_blank" ' is missing
b) possibly clicking is even partially disabled (pointerEvents='none' ?
     although right-klick "open in new tab")

**Comment by mmmatthew** [comment]
created issue in gallery library: https://github.com/lukasz-galka/ngx-gallery/issues/206
