### ISSUE TITLE
pls remove link "Check the MockUp" from www

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#95]
Since the Beta has reached some level now, that mock diverts attention of novice visitors - agreed ?

**Comment by mmmatthew** [comment]
I agree. the question is what to do with this landing page in the short term. As soon as Christian opens port 3001 we will use www.water-fountains.org for the stable version of the app. I would suggest moving all relevant text to the application itself or to the Github pages.

PS: this issue should have been created on https://github.com/water-fountains/wfplaceholder

**Comment by mmmatthew** [comment]
Option has been hidden
