### ISSUE TITLE
simply detail window bottom part

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#98]
![image](https://user-images.githubusercontent.com/1681677/48316533-47392900-e5e5-11e8-97e3-f7b34ce49b42.png)

The yellow is very technical for average users.

How about putting a question mark icon at  (1) and display the yellow text on "mouseover/click" ?

**Comment by mmmatthew** [comment]
yes, it is too technical. We could also put it at the bottom of the expandable area that contains all fountain properties. What do you think?

**Comment by ralfhauser** [comment]
Yes, at the bottom of expandable is fine too.

But then
2) name "Schaltfläche unten" to the specific "neueste Daten abrufen"

**Comment by mmmatthew** [comment]
Which element is "Schaltfläche unten"? And what is the "specific" "neueste Daten abrufen"?

**Comment by ralfhauser** [comment]
"Schaltflüche unten" is just a citation of your text. You probably mean the button left of (1)
