### ISSUE TITLE
Make wikipedia link more usable

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#99]
![image](https://user-images.githubusercontent.com/1681677/48316598-291ff880-e5e6-11e8-8a7f-9b31aeb2bc88.png)

**Comment by mmmatthew** [comment]
solved in referenced commit with type-based formatting

**Comment by ralfhauser** [comment]
Somehow, this didn't proprely get submitted
1) make this clickable ( target="_blank" )  ==> done
2) as this probably doesn't apply for all attributes (only show it if it really exists) Admitted for wikipedia, it exists, but how about "Rollstuhlgerecht"? 
3) Please make the first wikipedia sentence visible as per issue #61
